const ActionTypes = {
  // Azure
  AZURE_OK: 'AZURE_OK',
  AZURE_FAIL: 'AZURE_FAIL',
  AZURE_INCIDENTS: 'AZURE_INCIDENTS',

  // Datadog
  DATADOG_OK: 'DATADOG_OK',
  DATADOG_FAIL: 'DATADOG_FAIL',
  DATADOG_INCIDENTS: 'DATADOG_INCIDENTS'
}

export default ActionTypes